on:
  push:
    paths:
      - backend/**
      - VERSION
      - .github/workflows/**
  pull_request:
    paths:
      - backend/**
      - VERSION
      - .github/workflows/**
env:
  target_version: ''
  ARTIFACT_VERSION_TAG: ''
jobs:
  prepareEnvironment:
    name: Setup build job environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Determine artifact version
        run: echo "target_version=$(cat .\VERSION) >> $GITHUB_ENV"
      - name: Add version to artifact tag
        run: echo "target_version=$target_version.${{ github.run_number }} >> $GITHUB_ENV"
      - name: Add buildnumber to artifact tag
        run: echo ${{ env.target_version }}
      - name: Add version to artifact tag
        if: github.ref == 'refs/heads/develop'
        run: echo '-SNAPSHOT'
  testAndBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute Unittests
        run: gradle :backend:test
      - name: Build Jar
        run: gradle :backend:assemble :backend:check -x test
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: oc-server-jar
          path: backend/build/libs/.jar

  buildContainerImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Build and tag Docker image
        run: docker build ./backend -t diniMueter

