on:
  push:
    paths:
      - backend/**
      - VERSION
      - .github/workflows/**
  pull_request:
    paths:
      - backend/**
      - VERSION
      - .github/workflows/**
env:
  target_version: ''
  branch_name: ''
  full_version: ''

jobs:
  prepareEnvironment:
    name: Setup build job environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Determine artifact version
        run: echo "target_version=$(cat VERSION)" >> $GITHUB_ENV
      - name: Add version to artifact tag
        run: echo "target_version=${{ env.target_version }}.${{ github.run_number }}" >> $GITHUB_ENV
      - name: Add buildnumber to artifact tag
        run: echo ${{ env.target_version }}
      - name: Determine branch suffix [remove prefix]
        uses: frabert/replace-string-action@v1.2
        id: removeRefPrefix
        with:
          pattern: 'refs/(\w+)/(.*)'
          string: ${{ github.ref }}
          replace-with: '$2'
      - name: Determine branch suffix [normalize name]
        uses: frabert/replace-string-action@v1.2
        id: normalizeBranchName
        with:
          pattern: '[^a-zA-Z\d]'
          string: ${{ steps.removeRefPrefix.outputs.replaced }}
          flags: g
          replace-with: '-'
      - name: Determine branch suffix [write to env]
        run: echo "branch_name=${{ steps.normalizeBranchName.outputs.replaced }}" >> $GITHUB_ENV
      - name: Set full version [Part 1]
        run: echo "full_version=${{ env.target_version }}" >> $GITHUB_ENV
      - name: Set full version [Part 2]
        if: ${{ env.branch_name != 'master' }}
        run: echo "full_version=${{ env.target_version }}-${{env.branch_name}}" >> $GITHUB_ENV
      - name: Debug env
        run: echo ${{ env.full_version }}
  testAndBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute Unittests
        run: gradle :backend:test
      - name: Build Jar
        run: gradle :backend:assemble :backend:check -x test
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: oc-server-jar
          path: backend/build/libs/.jar

  buildContainerImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Build and tag Docker image
        run: docker build ./backend -t diniMueter

